#+title: RUST DOC FOR MYSELF

* Basic setup
Use cargo! Cargo is the package manager for Rust. You can install the rustup package on their official [[https://rust-lang.org/pt-BR/learn/get-started/][website]].

#+begin_src bash
  cargo new proj-name
  cargo build
  cargo run
#+end_src

* Variables
Variables are imutable by default in Rust.

#+begin_src rust
  fn main() {
      
      // x is imutable
      let x = 10;
      
      // This would return an error
      x = x + 2; 

      // y is mutable
      let mut y = 5;

      // This is ok, since y is mutable
      y = y + 2;
  }
#+end_src

** Constants
These are not only imutable by default, they are *always* imutable. You can't turn a const mutable.

#+begin_src rust
  fn main() {
      // There's no "const mut" in Rust
      const PI = 3.1415; 
  }
#+end_src

** Shadowing
You can overshadow the name of another variable. This means the new variable will take the name to itself until the end of the scope. This allows "mutation" of type, since we are creating a brand new variable. Mutability does not allow this.

#+begin_src rust
  fn main() {
      
      // imutable x
      let x = 10;
      
      // x value is overshadowed by the new x value below
      let x = x + 1;
      
  } // => x = 11
#+end_src

** Primitive Data types
- Integers :: can be signed or unsigned, varies in size.
  + i8, u8, i32, u32 etc
  + usize and isize are architecture-dependent
- Number literals :: if you want to write down hex, binary etc.
  + hex => 0xff
  + octal => 0o77
  + binary => 0b101001
  + byte => b'A'
- Floats :: for floating point values.
  + f64, f32
- Boolean :: binary logic.
  + bool
  + keywords => "true" and "false"
- Char :: single quotes.
  + char
- Tuple :: compound type of integers, can vary in size for each element.
  + (u32, u8, f32), for example
  + You can access the values in the tuple by var_name.index (from 0)
- Array :: all elements must have the same size, fixed length.
  + let a: [i32; 5] = [1, 2, 3, 4, 5]
  + acessing the array a[index]

* Functions
Defining functions is done with the *fn* keyword, followed by name, arguments and return type.

#+begin_src rust
  fn function_name(arg: Type) -> Type{
      // Instructions go here
      // Return value (expressions) can't have semi-colon
  }
#+end_src

* Control flow
If statements can be inside of variables. The rest is similar to C-like languages.

#+begin_src rust
  // Both result must have compatible types.
  let x = if condition { 6 } else { 7 };
#+end_src

You should use the *match* keyword for control flow with many possibilities.

#+begin_src rust
  fn main() {
      
      let a = 10;
      
      match a {
  	// You can match a single number
  	1 => 10,
  	// You can match multiple numbers
  	2 | 3 | 4 => 20,
  	// You can match in a range
  	13..=20 => 0,
  	// Default value
  	_ => 1,
      }

      // You can also assign match to a variable
      let boolean = true;
      
      let binary = match boolean {
  	false => 0,
  	true => 1,
      };
  }
#+end_src

** Loops
The *loop* keyword is useful for looping. You can use the *break* keyword to stop a loop and label them.

#+begin_src rust
  // -->o-- snip -->o--
  let mut a = 0;

  'my_loop_label: loop {
      if a == 9 {
  	break 'my_loop_label;
      }

      a += 1;
  }
#+end_src

You can also use the *while* keyword.

#+begin_src rust
  let mut a = 1;

  while a != 10 {
      number += 1;
  }
#+end_src

To iterate through a collection, the *for* keyword is better.

#+begin_src rust
  let arr = [1, 2, 3, 4, 5];

  for element in arr {
      println!("the value is: {element}");
  }

  // You can use a range
  for n in (1..10) { 
      // -->o--
  }

  // You can reverse the range with rev()
  for n2 in (1..10).rev() { 
      // -->o--
  }
#+end_src

* Ownership
Ownership is Rust's must unique and important feature to understand. This is what garantees memory safety without the need for a garbage collector.

** The Rules
- All values have an *owner*;
- There can only be *one* owner at a time;
- When the owner goes out of scope, the value is dropped.

*** The Variable Scope
The scope of a variable is how long it will exist in the program runtime. Variables will exist inside of the scope of brackets in which they were defined. After that, they are no longer valid.

#+begin_src rust
  {
      let a = 0; // a is valid from here on

  } // a is no longer valid
#+end_src

When variables need allocation, that is, are not done on the stack but on the heap, Rust uses the RAII principle, similar to C++.

#+begin_src rust
  {
    let s = String::from("Hiii!"); // s is valid from here on, memory is allocated

  } // s is no longer valid, memory is dropped automatically
#+end_src

When you bind a allocated variable to another, Rust will consider it no longer valid. This is used to avoid *double free* error.

#+begin_src rust
  {
     let s1 = String::from("UwU");
     let s2 = s1; // s1 is no longer valid here, only s2 exists.

  } // s2 goes out of scope, memory is freed
#+end_src

Assigning a new value to a variable will also free it.

#+begin_src rust
  {
     let mut s1 = String::from("Lalala!");
     s1 = String::from("Lololo!"); // original s1 is dropped, only the new s1 remains

  } // s1 goes out of scope 
#+end_src

If it is necessary to actually deeply copy heap data, we should use the *clone* method.

#+begin_src rust
  {
      let s1 = String::from("String");
      let s2 = s1.clone();
      // both s1 and s2 are valid and store the string

  } // s1 and s2 go out of scope
#+end_src

Primitive types (allocated on the stack) implement the *Copy* trait, so they are allowed to create copies of themselves.

*** Ownership and Functions
Values that are moved to functions, when on the heap, are no longer valid on the specific scope. If those values implement the Copy trait, they will remain valid until the end of the scope.

#+begin_src rust
  fn main() {
      let s = String::from("Rust is cool");
      
      take_ownership_function(s); // s moves into the function, no longer valid in this scope

      let x = 5;

      copy_function(x); // since i32 implements Copy, the value does not move, x is still valid in this scope
  } // x goes out of scope, nothing special happens to s since it was moved

  fn take_ownership_function(my_string: String) {
      // -->o-- snip 
  } // my_string goes out of scope, which held s's data, and is freed

  fn copy_function(my_int: i32) {
      // -->o-- snip
  } // my_int goes out of scope, nothing special
#+end_src

Returning a value can give ownership.

#+begin_src rust
  fn main() {
      let s1 = give_ownership_func();

      let s2 = String::from("Test");

      let s3 = take_and_give_back_func(s2); // s2 was moved
  } // s1 and s3 goes out of scope, s2 was moved, nothing special

  fn give_ownership_func() -> String {
      let my_string = String::from("Lalala");

      my_string // ownership goes to the variable s1 calling the function
  }

  fn take_and_give_back_func(a_string: String) -> String { 
      a_string // ownership goes to the function than goes to s3 that calls it
  }
#+end_src

*NOTE*: You can return multiple values in Rust using a tuple!

#+begin_src rust
  fn example_function(..args..) -> (..type.., ..type..) {
      // -->o-- snip

      (value_1, value_2)
  }
#+end_src

*** References and Borrowing

References are *like* pointers to a value that is owned by another variable. References always point to a valid value for the life of the reference. Using references, you don't take ownership of the value! This is called borrowing. Unlike pointers, it is not possible to have dangling references (compiler will complain).
#+begin_src rust
  fn main() {
      let s1 = String::from("Hi");

      let len = calc_length(&s1); // the & operator passes a reference to s1
      // s1 is still valid!

      println!("String: '{s1}', Size: {len}".);
  } // s1 and len goes out of scope

  fn calc_length(s: &String) -> usize { // Notice the type is followed by the & operator
      s.len()
  }
#+end_src

To modify a borrowed value, we must use the *&mut* keyword in the reference.

#+begin_src rust
  fn main() {
      // Assigning a mutable variable
      let mut s = String::from("I watched you change...");

      change(&mut s); // We use &mut to borrow and be allowed to modify the value!
  }

  fn change(a_string: &mut String) { // Remember the keyword!
      a_string.push_str(" into a fly!");
  }
#+end_src

*IMPORTANT!* If you do a mutable reference, you can only do it ONCE! You cannot do a mutable borrow on a value that had an imutable borrow that was not yet used!

- Rules of references :: basic rules you should remember
  + You can have either ONE mutable reference or any number of immutable references;
  + References must always be valid.

*** Slice
Slices are a type of *reference* (so, no ownership) to a sequence of elements in a collection, similar to Go slices.

#+begin_src rust
  let s = String::from("Hello world");

  // Slices are a piece of the original collection
  // Range can be any
  let hello = &s[0..5];

  // Slices can also be of the entire collection
  let all = &s[..];

  // It can be of any type of collection
  let arr = [1, 2, 3, 4, 5];

  let slice_arr = &arr[..2];
#+end_src

*NOTE*: String literals (not using the *String::from()* method) are just slices!

* Structs
For creating custom data types! Just like in C.

#+begin_src rust
  struct Animal {
      alive: bool,
      name: String,
      kg: u32,
  }

  // The instance of a struct can be mutable!
  // But the whole instance will have to be mutable, Rust does not allow
  // for specific fields to be set as mutable or immutable
  let cat = Animal { 
      alive: true,
      name: String::from("Katty"),
      kg: 5,
  };
#+end_src

It is possible to build functions to create instances of a struct.

#+begin_src rust
  struct Animal {
      alive: bool,
      name: String,
      kg: u32,
  }

  fn build_animal(alive: bool, name: String, kg: u32) -> Animal {
      Animal {
     	// These are short hands for not repeating arg_field:field each time
     	alive,
     	name,
     	kg,
      }
  }

  let cat_katty = build_animal(true, String::from("Katty"), 4);

  // You can reuse values of another instance of a struct with this syntax
  // This will cause the values of the other instance to be moved and so the original
  // instance can't be used
  let dog_katty = Animal {
      alive: false,
      ..cat_katty // The last fields will be the same as the cat_katty instance
  }
#+end_src

You can also use tuples to create new types!

#+begin_src rust
  struct Color(i32, i32, i32);
  struct 2DPoint(i32, i32);

  let black = Color(0, 0, 0);
  let origin = 2DPoint(0, 0);
#+end_src

*NOTE*: You can create Unit-like structs, structs with no fields. Simply do struct NameOfStruct.

** Associated functions
Methods are the associated functions that take the struct as input. Any associated function that is not a method is used for constructors generally.

#+begin_src rust
  struct Rectangle {
      w: u32,
      h: u32,
  }

  impl Rectangle {
      // This is a method
      fn area(&self) -> u32 { // &self is short for self: &self
  	self.w * self.h
      }

      // You can do non methods (associated functions)
      fn square(size: u32) -> Self {// Self will return struct of type Rectangle
  	Self {
  	    w: size,
  	    h: size,
  	}
      }
  }

  fn main() {
      let r = Rectangle {
  	w: 10,
  	h: 20,
      };

      let sq = Rectangle::square(5); // To call an associated function we use the :: syntax

      r.area(); // Returns the area using the method of the struct
      sq.area(); // Square is a type of Rectangle, so the methods are still valid for it
  }
#+end_src

* Enums
For stablishing the set of possible values.

#+begin_src rust
  enum Pets {
      Dog,
      Cat,
      Rabbit,
  }
#+end_src

You can create an instance of a Enum using the :: operator.


#+begin_src rust
  enum Pets {
      Dog,
      Cat,
      Rabbit,
  }

  let katty = Pets::Cat;
  let puggy = Pets::Dog;
#+end_src

You can call enums on functions, since it defines a type.

#+begin_src rust
  // This function will be able to receive all the
  // possible variants of the Enum Pets

  fn give_food(pet: Pets) {}

  give_food(Pets::Cat);
#+end_src

You can use the Enum to associate a specific value, with not need to create a struct.]

#+begin_src rust
  enum Pets {
      Cat(String),
      Dog(String),
  }

  let katty = Pets::Cat(String::from("Katty"));

  // Each Enum variant is also a constructor function
#+end_src

An very important enum in Rust is the *Option enum*! Feature for dealing with possible *null* values. Read the [[https://doc.rust-lang.org/std/option/enum.Option.html][docs]].

#+begin_src rust
  enum Option<T> { // As defined in the standard library
      None,
      Some(T),
  }

  // Since these are so useful, you can call them directly anywhere in the code
  let a = Some(10); // Type Option<i32>
  let b = Some('a'); // Type Option<char>
  let absent: Option<i32> = None; // Type can't be infered

  // Option<T> and T are different types, you cannot do operations between them
  // unless you convert them into one another
#+end_src

Enums can handle many different data types with ease.

#+begin_src rust
  enum IpAddr {
      V4(u8, u8, u8, u8),
      V6(String),
  }

  let home = IpAddr::V4(127, 0, 0, 1);

  let loopback = IpAddr::V6(String::from("::1"));

  // It's also possible to use a struct as the value associated with the variant in the Enum
#+end_src

Enums can be used with match to look for patterns.

#+begin_src rust
  // Example from the Rust book
  enum Coin {
      Penny,
      Nickel,
      Dime,
      Quarter,
  }

  fn value_in_cents(coin: Coin) -> u8 {
      match coin {
          Coin::Penny => 1,
          Coin::Nickel => 5,
          Coin::Dime => 10,
          Coin::Quarter => 25,
      }
  }

  // You can match for Some<T> and None aswell
  fn plus_one(x: Option<i32>) -> Option<i32> {
      match x {
  	None => None,
  	Some(i) => Some(i + 1),
      }
  }
#+end_src

TODO: Other stuff about this. Using if ... let is useful when you only want to match to a single possibility and ignore the rest.

#+begin_src rust
  let a = Some(5);

  if let Some(b) = a {
      println!("Lalala!");
  }

  // The above code is the same as
  match a {
      Some(b) => println!("Lalala!"),
      _ => (),
  }
#+end_src

* Common Collections

These are very common collections in Rust.

** Vector
To create a vector you use the Vec<T> for type and Vec::new() construction. Done on the heap.

#+begin_src rust
  let v: Vec<i32> = Vec::new();

  // i32 is the default integer type
  // Macro creates a vector of Vec<i32> type
  let v2 = vec![1, 2, 3];

  // You can use the push() method to push values to a vector
  let mut v3 = Vec::new();
  v3.push(4);
  v3.push(5);

  // You can use the get() method to acess a value from a vector
  let v4 = vec![1, 2, 3];
  let third: Option<&i32> = v.get(2); // type &i32 because it is a slice of the vector

  match third {
      Some(third) => println!("There is a third element: {third}");
      None => println!("No third element on the vector.");
  } // get() will return None when outside of bounds

  // Iterating over the values of a vector
  let v5 = vec![1, 2, 3, 4, 5];
  for i in &v5 {
      println!("{i}");
  }

  // To change a value of a reference we must use the * dereference operator
  let mut mut_v = vec![10, 20, 30];
  for i in &mut mut_v {
      ,*i += 50;
  }

  // You can use Enums together with vector if you want a variety of types
   enum SpreadsheetCell {
        Int(i32),
        Float(f64),
        Text(String),
    }

    let row = vec![
        SpreadsheetCell::Int(3),
        SpreadsheetCell::Text(String::from("blue")),
        SpreadsheetCell::Float(10.12),
    ];
#+end_src

** String

String were touched a bit before.

#+begin_src rust
  let mut s = String::new();

  // You can turn a literal into a String
  let s = "lalala".to_string();
  let s = String::from("lalala");

  // Strings are UTF-8 encoded
  let hello = String::from("你好");

  // You can grow a String with the push_str() method
  // push() adds a single character
  let mut s1 = String::from("foo");
  s1.push_str("bar");
  s1.push('a');

  // You can concatenate Strings with the + operator
  let a = String::from("lalala");
  let b = String::from("lololo");
  let c = String::from("lelele");

  let new_concat = a + "-" + &b + "-" + &c; // a was moved

  // You can do the same with format! macro
  let new_concat = format!("{a}-{b}-{c}");

  // You can iterate over a String
  for c in "abcdefg".chars() { // chars that make up the String
      println!("{c}");
  }

  for b in "abcdefg".bytes() { // bytes that make up the String
      println!("{b}");
  }
#+end_src

** Hash Map

A Hash Map is all about having a key and a value associated with each key.

#+begin_src rust
  use std::collections::HashMap;

  let mut scores = HashMap::new();

  scores.insert(String::from("Blue"), 10);
  scores.insert(String::from("Red"), 40);

  // Acessing values from the Hash Map
  let team_name = String::from("Blue");
  let blue_score = scores
      .get(&team_name) // returns an Option<&V>
      .copied() // Turn the Option<&i32> into Option<i32>
      .unwrap_or(0); // Sets score to 0 if the key doesn't have an entry

  // You can also iterate over a Hash Map
  for (k, v) in &scores {
      // -->o-- snip -->o--
  }
#+end_src

* TODO Error Handling
